version: '3.8'
services:
  web:
    image: httpd:latest
    container_name: desafio-apache-dio
    ports:
      - "80:80"
    volumes:
      - /data/apache:/usr/local/apache2/htdocs/
    networks:
      - minha-rede

networks:
   minha-rede:
     driver: bridge
